### ISSUE TITLE
No plugins to show

### ISSUE THREAD

**Issue by BFergerson** [dkandalov/live-plugin#134]
I've been able to successfully use the live-plugin via the "Scratches and Consoles" dropdown but not via `.live-plugins` folder. I have both `Run plugins on IDE Start` and `Run Project Specific Plugins` checked, but it still doesn't seem to pick up my plugin.

You can see my setup here:
![image](https://user-images.githubusercontent.com/3278877/167363747-f61a16f8-70db-4903-a947-349a250a8591.png)

IDE Version: Build #IU-221.5080.210, built on April 12, 2022
LivePlugin Version: 0.8.1 beta

---

Is there something else I need to do to make it recognize plugins in `.live-plugins`?

**Comment by BFergerson** [comment]
Looks like a folder is necessary with the Kotlin script being named `plugin.kts`. It still shows `No plugins to show` but maybe that is by design.

**Comment by dkandalov** [comment]
> Yes, plugins need to be in a subfolder and the plugin file should be called `plugin.kts`. For example `.live-plugins/hello-world/plugin.kts`.
Hehe, yes I just typed just that :) It is by design, but I think it is a valid issue though and I got myself confused as well.

Maybe all files under `.live-plugins` should be runnable. The only problem I can think of is that in plugins with multiple files "Run Plugin" action will attempt to run the current file even though it's not the plugin entry point (i.e. not `plugin.kts`). On the other hand, multiple files don't have IDE support for Kotlin and I guess are not very common anyway, so it might be worth just doing that. Another option is to have two separate actions, one running plugin and one for running the current file 🤔
