### ISSUE TITLE
Copy Paste files into live plugin folder

### ISSUE THREAD

**Issue by shpakkrll** [dkandalov/live-plugin#166]
Talking about LivePlugin Tab tool.
It was hard to locate live plugin location on filesystem.
Then, some dedicated time later, I saw `show($pluginPath)`, after that it was easy to move files into plugin folder.
However the process may be simplified by allowing copy&paste feature.

Just my experience. Kudos!

**Comment by dkandalov** [comment]
Thank you for the feedback!
Yes, the plugins tool window is a bit too minimal and being able to paste files is a useful feature.

At the same time the plugins are also available in the Project view tool window under `Scratches and Consoles -> Live Plugins`. Copy and paste should work there. In general, this is a better place for live plugins because it's consistent with "IDE Consoles" but it's less convenient and discoverable.

There is also a built-in `Copy Paths` action (cmd+shift+C or ctrl+shift+C) which works in the Plugins tool window.

**Comment by shpakkrll** [comment]
Thanks, will take a look into it
