### ISSUE TITLE
Plugin has stopped working for IntelliJ IDEA 2023.3.1

### ISSUE THREAD

**Issue by mbwanajm** [dkandalov/live-plugin#172]
<img width="265" alt="Screenshot 2023-12-14 at 17 12 32" src="https://github.com/dkandalov/live-plugin/assets/369346/987d7af7-a4c1-4bf0-86df-97f02f561360">

**Comment by dkandalov** [comment]
Thank you for reporting this. I haven't upgraded to 2023.3.1 yet. Will have a look!

**Comment by dkandalov** [comment]
This might be related to this plugin verifier issue https://youtrack.jetbrains.com/issue/MP-6157/Plugin-verifier-doesnt-track-transitive-dependencies which incorrectly marks plugin as incompatible.

Where do you see this message? In IntelliJ 2023.3.2 RC I can't see LivePlugin in the plugins marketplace at all :(

You should still be able to install the plugin by downloading it from here https://plugins.jetbrains.com/plugin/7282-liveplugin/edit/versions and using `Install Plugin from Disk...` action.

**Comment by davecazz** [comment]
confirming that if you have livePlugin installed in 2023.2.x and upgrade to 2023.3.x the plugin is listed as an installed plugin, but it disables the plugin and marks it as not compatible. when I install a jetbrains ide from scratch, I cant find it in the marketplace at all, probably because it filters incompatible plugins.

you can also see an incompatibility warning in the web page for LivePlugin https://plugins.jetbrains.com/plugin/7282-liveplugin if you have a 2023.3.x ide installed. "Not compatible with the version of your running IDE (PyCharm 2023.3.1, CLion 2023.3.1, DataSpell 2023.3.1)
"

**Comment by mbwanajm** [comment]
I concur with @davecazz, I had LivePlugin installed before upgrading to 2023.3.1, it was disabled immediately after the upgrade restart. I am not quite sure how IntelliJ plugin compatibility works, but from here [LivePlugin Marketplace download page](https://plugins.jetbrains.com/plugin/7282-liveplugin/versions) version 0.8.6 beta of the plugin is given the compatibility range of 231.7515.13—232.* also shown as the range 2023.1 — 2023.2.5.
Just a wild guess here, could these be some manually written metadata in the plugin?
<img width="563" alt="Screenshot 2023-12-22 at 09 30 35" src="https://github.com/dkandalov/live-plugin/assets/369346/7ddcb7e8-c04b-47e8-94a8-7f5a77cf5f98">
<img width="993" alt="Screenshot 2023-12-22 at 09 21 19" src="https://github.com/dkandalov/live-plugin/assets/369346/ae2e2170-2f8c-4357-9f3c-814ee0829346">

**Comment by dkandalov** [comment]
@mbwanajm you're right! I'm not sure how the plugin ended up with an upper version in compatibility range, because I deliberately don't specify it `<idea-version since-build="231.7515.13" />`.

I was able though to edit the range for version 0.8.6 on marketplace website so it's now just 231.7515.13+ and should be marked as compatible with the latest IntelliJ versions.

**Comment by mbwanajm** [comment]
Great this now works.. I have tested it on  2023.3.2
