### ISSUE TITLE
Nothing happens when plugins run in PhpStorm

### ISSUE THREAD

**Issue by grimalschi** [dkandalov/live-plugin#49]
I just see "loading Plugin" in status bar, then it hide, and nothing is happens - no messages in "Events" no popups and other.
GIF: https://yadi.sk/i/yD6dzgwXeAatP
What can i do with this? Where do i can see logs or something else?

Я вижу только "Loading Plugin" на панели снизу, потом она скрывается и после этого ничего не происходит. Никаких сообщений, никаких попапов, ничего.
Гифка: https://yadi.sk/i/yD6dzgwXeAatP
Что с этим можно сделать? Где я могу посмотреть логи, или еще что-то?

**Comment by dkandalov** [comment]
Hello,

Thanks a lot for reporting this and the screencast. The reason is that latest version of plugin depends on com.intellij.openapi.compiler.CompilationStatusAdapter class which is not bundled with PhpStorm. I'll fix the problem and will release updated version.
Just in case there is IDE log which you can find in Main Menu -> Help -> Show Log (although in this case there are no errors logged).

Спасибо большое за баг и скринкаст. 
Проблема в том что последняя версия плагина использует класс CompilationStatusAdapter, которого нет в PhpStorm. В принципе в этом классе нет необходимости. Я уберу зависимость и зарелижу новую версию.
На всякий случай если это пригодится, в IDE есть общий лог в Main Menu -> Help -> Show Log (хотя в данном случае ошибок там не было).

**Comment by dkandalov** [comment]
Uploaded version 0.5.2 beta (works for me in PhpStorm 8.0.2)

**Comment by grimalschi** [comment]
Yes, it works! Many thanks for the quick response!
