### ISSUE TITLE
Cannot inspect Scala files 

### ISSUE THREAD

**Issue by jpsacha** [dkandalov/live-plugin#52]
I was attempting to create a simple plugin that will find recursive calls in Scala code. Based on example for Java files:
https://gist.github.com/dkandalov/7248184

In live-plugin Scala psiItems cannot be cast to `ScalaFile` etc. For instance:

```
psiItem instanceof org.jetbrains.plugins.scala.lang.psi.api.ScalaFile
```
always returns `false` even when a psiItem is an instance of `ScalaFile` (possibly because they are loaded by a different class loaders).

Please fix this so live-plugin could be used in Scala projects.

**Comment by dkandalov** [comment]
I think you're right and if ScalaFile class is found by plugin at runtime but doesn't match class of PsiItem, then it must be from different classloader. The question is how additional ScalaFile class loaded into plugin because scala plugin classes are not loaded by default.

This is the gist that works for me https://gist.github.com/dkandalov/39fcfe52c03e6bc4b48a
It uses "// depends-on-plugin org.intellij.scala" to add IntelliJ scala plugin classloader as one of plugin.groovy parent classloaders  ("org.intellij.scala" is id of scala plugin). Please note this is a prototype and it might not find all the cases of recursive functions in scala.

If you get to do something interesting with scala psi, please give a shout and I'll add link in readme.md :)

Thanks a lot for reporting the problem.
I'll update readme/plugin examples to mention "depends-on-plugin" directive and will publish the gist above.

**Comment by jpsacha** [comment]
Adding `depends-on-plugin` made it work.
I created a Scala version of the plugin, with some fixes:
https://gist.github.com/jpsacha/9864e30dc884683bee18

**Comment by dkandalov** [comment]
Thanks a lot. I updated github readme.
