### ISSUE TITLE
Auto-import and syntax checking not working

### ISSUE THREAD

**Issue by vjpr** [dkandalov/live-plugin#60]
Should it be possible for auto-import, code completion, syntax checking to work?

Doesn't work for me with Scala or Groovy...

**Comment by dkandalov** [comment]
Code completion and syntax checking should work. This is assuming that:
 - it's java based IDE (IntelliJ IDEA or Android Studio)
 - current project has JDK configured
 - to see IJ and LivePlugin classes, in Plugins toolwindow click `Settings -> Add IDEA/LivePlugin jars to project`

I'm not sure what you mean by "syntax checking" though. If you press `ctrl+alt+shift+H` in editor with plugin, what is the "Highlighting level" it shows?

There is a separate problem with auto-import which doesn't work in non-project files since some change in IJ. I'll try to re-enable it for LivePlugin files.

Thank you for reporting this. Except for fixing problems with it, I could probably add some hints to plugin editor.
