### ISSUE TITLE
When will the newer version be available?

### ISSUE THREAD

**Issue by aristotll** [dkandalov/live-plugin#74]
I am excited about the Kotlin support.(Although not so happy about the drop support of scala and clojure(maybe)).

There seems a lot  refactoring and much Java based code has been converted to Kotlin, so when will the newer version be available?

**Comment by dkandalov** [comment]
There is no particular plan for releases because it's just a pet project 🙂 
Probably in couple weeks. I can also commit a `.zip` file with new version of the plugin.

Overall, Kotlin support should already work. At the moment I'm trying to use it for couple things to flesh out potential problems. One thing I found is that using existing code from `PluginUtil` doesn't work very well because groovy and kotlin are not designed for interop with each other. So it probably needs rewriting in Kotlin.

Regarding scala and clojure, I have no data about how many people really use them with liveplugin. My guess was that very few, but I might be wrong and may be should put support back 🤔
