### ISSUE TITLE
how to unregisterAction ?

### ISSUE THREAD

**Issue by bluelovers** [dkandalov/live-plugin#84]
```kt
import liveplugin.unregisterAction

unregisterAction("CHS To CHT")
unregisterAction("CHT To CHS")
unregisterAction("CHS To CHT (2)")
unregisterAction("CHT To CHS (2)")
unregisterAction("CHS To CHT (unsafe)")
unregisterAction("CHT To CHS (unsafe)")
```

but

```
error: unresolved reference: unregisterAction
import liveplugin.unregisterAction

error: unresolved reference: unregisterAction
unregisterAction("CHS To CHT")

....
```

**Comment by dkandalov** [comment]
Sorry, I somehow managed to miss this issue :( but I guess it's better to answer late than never.

I normally don't unregister actions manually because `registerAction` will unregister action anyway if there is one with the same id.

In groovy the imports are
```
import static liveplugin.PluginUtil.registerAction
import static liveplugin.PluginUtil.unregisterAction
```

There is even better way to unregister actions (and other things) by using `pluginDisposable`, e.g.
```
registerAction("CHS To CHT", "ctrl alt shift F12", null, "CHS To CHT", pluginDisposable) { /*...*/ }
```
where `pluginDisposable` is a variable which exists until mini-plugin is re-evaluated and on re-evaluation it will dispose all objects created during previous evaluation.
